### ISSUE TITLE
TypeConverter other than for primitives are not supported yet

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#6] opened 2017-11-15 02:37 UTC
@igarashitm commented on [Mon Oct 30 2017](https://github.com/atlasmap/atlasmap-runtime/issues/248)

https://github.com/atlasmap/atlasmap-runtime/blob/ce498616965254723428641ab5c03ed80cff4d40/atlas-core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java#L279-L306

Yes it's definitely TODO. Even [DateConverter](https://github.com/atlasmap/atlasmap-runtime/blob/ce498616965254723428641ab5c03ed80cff4d40/atlas-core/src/main/java/io/atlasmap/converters/DateConverter.java) is not available.

**Comment by rohanmars** [comment] 2017-11-28 18:06
@igarashitm is this issue only focused on adding DateConverter support?

**Comment by igarashitm** [comment] 2017-11-28 19:15
@rohanmars nope, this is to implement exactly this `TODO`
https://github.com/atlasmap/atlasmap-runtime/blob/ce498616965254723428641ab5c03ed80cff4d40/atlas-core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java#L304-L305

`DateConverter` is just an example (well, right now it's the only one though...). All the OOTB converters other than primitives should be invoked from here.

**Comment by rohanmars** [comment] 2017-12-13 03:31
@igarashitm I have implemented an approach that uses the annotation (AtlastConversionInfo) values to determine which conversion method to actually use in the conversion service. Is this an okay approach with you? It will simplify the solution I believe and help on #114 

Basically, when the conversion service loads the converter classes it now builds a map of converter methods using reflection, keyed by source/target field types. Then when the converterType method is called it looks up which method it should invoke from the map and uses the saved Method reference to invoke using refection. That way new conversion methods can be added simply by adding methods to the AtlasConverter class and annotating them accordingly. No update to the converter service would then be required.

I might need to slightly change the key object include the class names also (if they are specified on the annotation) to support multiple use cases that map to the COMPLEX fileldType but having different concrete impl classes. This is currently the case for the existing DateConverter, however, I think that this class needs to be improved anyway so that might not be required for that specific converter but probably should be supported anyway.

I was thinking also to remove the AtlasPrimativeConverter interface, I think that is unnecessary now. Do you have any thoughts as to why we should keep it if I change to use the reflection based approach?

**Comment by rohanmars** [comment] 2017-12-13 07:59
@mattrpav what you think about my proposed changes?

Upon deeper analysis the targetType class information is not readily available and/or not necessarily passed in the right places. There is a convertType method which contains the target class name (I assume) but this not currently implemented (and there are no places that call it).

The issue is when a field is marked as a COMPLEX type it would be advantageous to record the actual associated class with the converter method. That way multiple converters could exist for the COMPLEX use case to/from a different type.

Maybe it's better to leave full support of a COMPLEX type to another issue. It would mean that the current DateConveter would only support conversions between existing field types (except COMPLEX).

**Comment by mattrpav** [comment] 2017-12-13 11:50
+1 I’m in favor of this approach. It sounds similar to how Camel works for comparison. Also, the FieldActions have a similar approach. 

I think we need to be clear what ‘Complex’ means. From inspection POV, it means a holder of other fields. For conversion, I think supporting  a matter of “does a converter exist for my exact class name” vs trying to accept

**Comment by igarashitm** [comment] 2017-12-13 18:17
@rohanmars that approach sounds right to me, but want to look at the prototype to have deeper understand.

w/r/t COMPLEX, I think we currently stick to not use COMPLEX as a final field type. For UI COMPLEX field is a container of fields, not a mappable field. UI never creates a mapping using COMPLEX field type. So having COMPLEX as a field type of converter/fieldaction is a bug (i.e. DateConverter has bugs).
Changing this policy causes huge impact through UI, and I don't think we have enough feedback gathered to decide if we should do that or not. I think this was the conclusion in our discussion @mattrpav ?

**Comment by rohanmars** [comment] 2018-01-10 19:20
I'm proposing an update to this approach. Essentially the approach is to , a new attribute "format" on the FieldType mapping element. This would then be passed down into the relevant converter method if specified. Each converter can then make sense of the format field as relevant for the specific use case.  The especially makes sense for the boolean and date to string conversions and potentially for the number types too.

This change would require some changes to method signatures to pass down the format attribute value (currently only fieldTypes are passed into the conversion service). Additionally, a converter method would need to provide a 2 arg method signature (the last being a format string) if such method wants to be passed format info.

```
<Mapping xsi:type="Mapping" mappingType="Map">
   <InputField xsi:type="ns2:JavaField" path="/stringField" fieldType="String"  format="MM/dd/yyyy" />
   <InputField xsi:type="ns2:JavaField" path="/dateField" fieldType="Date" />
</Mapping>
```
or for boolean

```
<Mapping xsi:type="Mapping" mappingType="Map">
   <InputField xsi:type="ns2:JavaField" path="/stringField" fieldType="String"  format="true|TRUE" />
   <InputField xsi:type="ns2:JavaField" path="/boleanField" />
</Mapping>
```

The format value is converter specific. For Date it's likely an ISO string format, for booleean, a regex for example. 

Additionally the out-of-box converters would come with default format specifications which would be used if the user hasn't specified them.

**Comment by mattrpav** [comment] 2018-01-10 19:48
@rohanmars I like the flexibility. In my mind, the majority of converters don't need a format (short -> int, long -> double, etc) However, the format piece would allow a decent level of flexibility in the converters that have a default convention (such as String -> Boolean) and of course the date(s).  

Combine this with the longer term piece of being able to disable auto-conversion on a per-mapping basis and allow users to provide their own conversion and I believe we can reasonably cover the last few edge cases users will throw at AtlasMap.

**Comment by igarashitm** [comment] 2018-01-11 19:33
@rohanmars It sounds like a good idea, but it looks like a bigger enhancement than the bug fix targeted for this issue. Can it be achieved in a separated thread apart from this one? or is it mandatory to fix this bug?

**Closed** 2018-02-02 18:33 UTC
Labels: cat/bug, module/runtime
