### ISSUE TITLE
A Target field in a nested collections is not supported

### ISSUE THREAD

**Issue by LimonBezSahara** [atlasmap/atlasmap#1746] opened 2020-02-05 10:01 UTC
Will there be support for Target fields in a nested collections? I can do it in interface (create mapping), but it doesn't work in a project.

**Comment by igarashitm** [comment] 2020-02-05 14:37
Basic support for target nested collection is already in.
Can you provide a bit more info:
* which version you tried?
* example document and/or mapping definition?

**Comment by LimonBezSahara** [comment] 2020-02-07 08:19
I tried version 1.43.4
What was wrong with my try?
[Example.zip](https://github.com/atlasmap/atlasmap/files/4169655/Example.zip)

**Comment by igarashitm** [comment] 2020-02-07 15:34
Thanks, it looks like a bug.

@rkorytkowski do you have a room to take a look? it seems there're some issues on both of UI and runtime, once I import the .adm file Split transformation is added for all collection mappings, where symmetric collection mapping (for each) is recognized as a one-to-many in UI, so like source collection is ignored.

**Comment by rkorytkowski** [comment] 2020-02-14 13:31
@LimonBezSahara, thanks for reporting the issue. Could you please provide the source document? I see you only provided the target document. I've been experimenting with the input document, but I have not yet hit an issue other than misbehaving UI when importing ADM.

**Comment by LimonBezSahara** [comment] 2020-02-15 06:52
@rkorytkowski, thanks.
It's my example. May be it's my mistake, But I can't understand, what I do wrong.
[Source_1-43-4.zip](https://github.com/atlasmap/atlasmap/files/4207831/Source_1-43-4.zip)

**Comment by rkorytkowski** [comment] 2020-02-20 12:48
@LimonBezSahara I've looked at the source and the target documents you provided and it looks to me as if the source was correctly transformed. I might have missed something. Could you please clarify what's your expected outcome for the given example? Where is the issue?

I've created a test case with your example: https://github.com/rkorytkowski/atlasmap/commit/23b32df83225f8a0676e3e4156f750f3f77ba551

**Comment by LimonBezSahara** [comment] 2020-02-20 14:51
@rkorytkowski I tried to use this not in a java class, but in a blueprint. And I use the corresponding dependence for version 1.43.4. And I received an error message "A Target field in a nested collections is not supported", when I use my map file. How can I understand where the problem is?

**Comment by rkorytkowski** [comment] 2020-02-20 14:56
@LimonBezSahara, do you have some source code to share to reproduce the error message?

**Comment by rkorytkowski** [comment] 2020-02-21 11:52
@LimonBezSahara, the error message you quoted has been removed entirely from source code, thus we think you are using an older version of atlasmap in your blueprint project. Please share your setup so we can provide further assistance.

**Comment by rkorytkowski** [comment] 2020-02-21 11:55
The UI issue has been addressed in https://github.com/atlasmap/atlasmap/pull/1796 Or else one can go around it by simply refreshing a browser after loading the adm file.

**Closed** 2020-02-21 12:59 UTC
Labels: cat/bug, group/runtime, group/ui, prio/p1
