### ISSUE TITLE
[RFE] Default Values for target document 

### ISSUE THREAD

**Issue by Shrishti1234** [atlasmap/atlasmap#3660] opened 2022-01-13 07:22 UTC
In one of my use case I need to set some default values for complex data type in target document. For setting default values currently there is no way. 

![image](https://user-images.githubusercontent.com/39737814/149282528-754cce04-96c7-4107-8098-d7e663f8e74a.png)

In above screenshot in targetDoc, "relatedParties" is a collection of objects in which some values are hradcoded and some parameteres will be mapped to source doc.

**Comment by igarashitm** [comment] 2022-01-13 13:18
Where are those default values supposed to be defined? in the schema? in that case it's possibly a duplicate of #719
Another idea came to my mind is to attach a template document at design time, would need a separate enhancement request issue.

**Comment by igarashitm** [comment] 2022-01-13 13:23
> will be mapped to source doc

Did you mean target doc? source doc is read only

**Comment by Shrishti1234** [comment] 2022-01-14 04:30
> > will be mapped to source doc
> 
> Did you mean target doc? source doc is read only

No, some fields of target doc are mapped to source doc and some have default values.

**Comment by igarashitm** [comment] 2022-01-14 11:53
Duplicate of #719

**Closed by igarashitm** 2022-01-14 11:53 UTC
Labels: cat/enhancement, wontfix
