### ISSUE TITLE
Could not find document for mapped field 'email' at URI atlas:json:sample after hitting refresh

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#1455] opened 2019-11-05 18:03 UTC
with Standalone 4.12.10
1. set source:
```
<record>
    <age>40</age><first_name>Stevie</first_name><last_name>Probate</last_name><email>sprobatepm@parallels.com</email><gender>Male</gender>
</record>
```
2. set  target:
```
{
    "name":"",
    "surname":"",
    "email":""
}
```
3. Create a field mapping between 2 fields
4. hit refresh
--> `Could not find document for mapped field 'email' at URI atlas:json:sample` error is displayed
![Screenshot from 2019-11-05 19-02-54](https://user-images.githubusercontent.com/1105127/68233146-e4fbe400-fffe-11e9-84b7-c8bf6ec5afb7.png)

**Comment by apupier** [comment] 2019-12-03 12:47
Inside VS Code, the issue is a bit less visible as we were able to drive users to another path (avoid refresh) in the most common case. it remains a problem in a case (closing/reopening the editor) https://issues.jboss.org/browse/FUSETOOLS2-71

Any estimation when this issue can be worked on?

**Comment by igarashitm** [comment] 2020-01-30 00:24
Duplicate of #1710

**Closed by igarashitm** 2020-01-30 00:24 UTC
Labels: cat/bug
