### ISSUE TITLE
Missing negation in error message

### ISSUE THREAD

**Issue by akieling** [atlasmap/atlasmap#179] opened 2017-09-18 14:57 UTC
**Current behavior**
Error message: "Conversion between source and target types is supported"
**Expected behavior**
Error message: "Conversion between source and target types is not supported"

Original issue: [syndesis-ui#677](https://github.com/syndesisio/syndesis-ui/issues/677)

**Comment by igarashitm** [comment] 2017-09-18 15:06
The message is coming from here - https://github.com/atlasmap/atlasmap/blob/master/atlas-api/src/main/java/io/atlasmap/spi/AtlasConversionConcern.java#L21

it's label is 'NONE', so looks like matching with the message. The problem is that the 'NONE' shouldn't be displayed as an error.

**Comment by igarashitm** [comment] 2017-09-18 15:08
Or it's possible that the wrong error message is chosen where there actually is an error.

**Comment by akieling** [comment] 2017-09-18 15:12
@igarashitm I'm having trouble reproducing this issue when running atlasmap. Please add steps to reproduce if you can.

**Comment by igarashitm** [comment] 2017-09-18 15:27
1. open an example integration "Twitter to Salesforce Example"
1. open data mapper step
1. click currentUserRetweetId from source and AccoundId from target
1. then you'll see duplicate message (#127)

And it looks like yet another bug, showing an error on a simple long>String conversion, which should be supported by the OOTB converters.
https://github.com/atlasmap/atlasmap/blob/master/atlas-core/src/main/java/io/atlasmap/converters/LongConverter.java#L145

**Comment by akieling** [comment] 2017-09-18 15:30
@igarashitm I'd like to reproduce the issue only running atlasmap.

**Comment by igarashitm** [comment] 2017-09-18 16:21
with addMockJavaSources = true in data.mapper.example.host.component.ts, you can see some more example source objects in the canvas.

But I don't see the same error if I run standalone atlasmap. Long>String map never shows an error. I suspect the old data for the java inspection result is somehow fed into atlasmap within syndesis.

Closing as this is not an atlasmap issue.

**Closed by igarashitm** 2017-09-18 16:21 UTC

**Comment by akieling** [comment] 2017-09-18 16:24
@igarashitm What do we do with syndesis-ui#677?

**Comment by igarashitm** [comment] 2017-09-18 16:32
@akieling we need to investigate further why it only happens within syndesis.
