### ISSUE TITLE
Source or target Modifications on the top of an existing adm file

### ISSUE THREAD

**Issue by Ruby-Kamboj** [atlasmap/atlasmap#3636] opened 2022-01-04 12:43 UTC
### Discussed in https://github.com/atlasmap/atlasmap/discussions/3635

<div type='discussions-op-text'>

<sup>Originally posted by **Ruby-Kamboj** January  4, 2022</sup>
Hi ,

We are doing a POC to check if atlas map can fulfil our business need to transform and enrich a JSON document to XML and we have found it quite promising  It is able to cover all our requirement but just one doubt we have stuck with is below, would really appreciate your help on.

Can we add or delete fields in the source and/or target schema without resetting the schema imports completely. Right now I do not see any option on atlas map UI to do that if I reset any schema, all mappings are gone and Have to redo whole mapping process which can be tedious due to complex mapping structures and tons of data fields.

This is an important scenario if in future there is a business need to just add mapping for one field on the top of existing mappings(adm file).

I have explored using atlas map version 3.1.8.</div>

**Comment by Ruby-Kamboj** [comment] 2022-01-10 13:34
update please

**Comment by igarashitm** [comment] 2022-01-10 14:03
Duplicate of #1417

**Closed by igarashitm** 2022-01-10 14:03 UTC
Labels: wontfix
