### ISSUE TITLE
Data loss on reload

### ISSUE THREAD

**Issue by AbbassFaytaroony** [atlasmap/atlasmap#936] opened 2019-05-20 05:22 UTC
Some times, when i reload the app, all imported documents disappear. I could not find a pattern by which the error occurs, however, i can replicate it by importing source/target documents, then reloading, repeat until it occurs. 
No errors are being thrown, so after debugging all i got is that size of file inside the .gz is 2GB. it seems there is an error in inflation/compression process on mapping update.

**Comment by igarashitm** [comment] 2019-05-20 12:45
could be same root with #935

**Comment by pleacu** [comment] 2019-08-05 19:05
Closing this as a duplicate of https://github.com/atlasmap/atlasmap/pull/1164
Please reopen if you can get this to fail again.

**Closed by pleacu** 2019-08-05 19:05 UTC
Labels: cat/bug, group/runtime, group/ui, prio/p1
