### ISSUE TITLE
Parameter input box for Repeat one-to-many transformation disappear after export/import

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2609] opened 2021-03-19 12:20 UTC
It seems this happens only if I don't input for the count. If I put a number there it successfully restored.
![atlasmap](https://user-images.githubusercontent.com/265462/111778737-88b00200-888b-11eb-8a7a-bc77ea0f515e.gif)

We might want to put `1` as a default value if none is provided from user.

It might be related to https://issues.redhat.com/browse/ENTESB-16032

**Comment by pleacu** [comment] 2021-03-19 17:01
Hey @igarashitm - this is likely an error but wanted to check.  Currently (master) you don't get the multiplicity transformation select menu if your are 1-1 (have to be 1-many or many to one).  Does CopyTo and Repeat apply one-to-one?

**Comment by igarashitm** [comment] 2021-03-19 17:04
No they should apply only for one-to-many.

**Comment by pleacu** [comment] 2021-03-19 17:09
Ok - so the example in the issue is incorrect as its establishing a 1-1 (city to city).  It should be one-to-many.  Also - the multiplicity  transformation select is inhibited if it's in a collection (like city to city).  Is that also correct?

**Comment by igarashitm** [comment] 2021-03-19 17:24
nope, the target is in collection, means it's one-to-many

**Comment by pleacu** [comment] 2021-03-19 19:22
Ok - still need a little help :)
In this case the source is in a collection as well as the target - is it still one to many?  Shouldn't it be `TransitionMode.FOR_EACH`?
And if it is FOR_EACH - it should not have the multplicity select, right?

**Comment by pleacu** [comment] 2021-03-19 19:48
@igarashitm - I have a trivial fix for the empty repeat field (I needed to upcase the `integer` field before defaulting).  The default code sets all number fields to 0.  In my version (and 2.1.6) - you don't get the multiplicity action pull-down menu for city-city (because of collection to collection).  if this is an error we can close this issue with my upcoming default integer fix and create a new issue.

**Comment by igarashitm** [comment] 2021-03-19 20:18
Note that the source field here is `/order/address/city` which is **not** in collection, as opposed to the target collection field `/addressList<>/city` which is in collection, which makes it one-to-many. Yes if both of them are collection then it is for-each mode.

**Comment by pleacu** [comment] 2021-03-19 20:32
*ugh* - yup - I was grabbing the wrong `city` - sorry.  This should fix this issue...

**Closed** 2021-03-19 20:40 UTC
Labels: cat/bug, group/ui, prio/p1
