### ISSUE TITLE
Upgrade to Camel 3

### ISSUE THREAD

**Issue by zregvart** [atlasmap/atlasmap#1654] opened 2020-01-10 16:30 UTC
At github.com/syndesisio/syndesis we're working on a branch to update to Camel 3.x. We noticed in some of the tests that use `camel-atlasmap` component that there's an issue when upgrading to Camel 3 as the AtlasMap component is based on `DefaultComponent` which has been [moved to a different package in Camel 3.x](https://camel.apache.org/manual/latest/camel-3-migration-guide.html#_migrating_custom_components).

Any plans on upgrading AtlasMap's Camel support to 3.x?

**Comment by igarashitm** [comment] 2020-01-10 16:35
We have a plan to have both camel2 and camel3 for a while, and have a maven profile to build them:
https://github.com/atlasmap/atlasmap/issues/1533

**Comment by igarashitm** [comment] 2020-01-10 18:33
Duplicate of #1533

**Closed by igarashitm** 2020-01-10 18:33 UTC

**Comment by rvnyk** [comment] 2020-02-20 13:50
Is there an ETA for atlasmap camel 3 support?
