### ISSUE TITLE
Add property scope in UI

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2209] opened 2020-06-29 14:51 UTC
See #2197 and #2117 

Allow user to choose a source document for scoping properties, which retrieves the properties within associated document scope. It would a dropdown box showing a list of Document name, and fill Document ID into PropertyField. The scope should be optional. Also, the special scope `camelExchangeProperty` should be the one of available scope.

**Comment by pleacu** [comment] 2020-07-22 20:41
@igarashitm - so on the `Create Property` dialog, users would be able to choose the source document to which it applies.  By optional then it would not have a default value.  WHen they click on it they see all loaded source panel documents + `camelExchangeProperty` - is that correct?

**Comment by igarashitm** [comment] 2020-07-22 21:01
Right, and whether to show "Current Message Header" explicitly or just have a blank item would be a UXD matter. Either way scope could be omitted. Or it's even fine to populate `current` explicitly.
https://github.com/atlasmap/atlasmap/blob/master/camel3/src/main/java/org/apache/camel/component/atlasmap/CamelAtlasPropertyStrategy.java#L38

**Comment by pleacu** [comment] 2020-07-23 13:29
@igarashitm - What would be a good hover-help for this?  Also - what's a good label?  Something simple like:

Scope: _____________________________
or
Camel Header Scope: ___________________________________

hover: 'Define the source document or exchange property for Camel Atlasmap headers associated with this property.  ?????

**Comment by igarashitm** [comment] 2020-07-23 13:59
I would avoid a word "Camel" for the general description like hover, since AtlasMap runtime in general is not limited to Camel. Eventually a list of scope might have to be configurable, but it's for future.
I would think something like "Choose property scope" is sufficient, or it would have to explain longer like "If it runs with Camel, blabla...". I think it's OK to leave it to User Guide.

**Comment by pleacu** [comment] 2020-07-27 19:38
Hey @igarashitm 
   I've got the UI code working but have an issue/ question on the generated JSON for the property scope.   The class `io.atlasmap.v2.Property` defines three fields -  `value`, `name`, `fieldType`.   The class `io.atlasmap.v2.PropertyField` defines a lot more - including `scope`.   This property UI dialog:

![sc1](https://user-images.githubusercontent.com/2981421/88583649-83612700-d01e-11ea-8100-ff5de6cdc799.png)


   Generates the following fragment:

   `"properties":{"property":[{"name":"paul","value":"rat","fieldType":"STRING"}]}`
 
   When I add property `paul` to the mapping I get the following fragment:

![sc2](https://user-images.githubusercontent.com/2981421/88583701-983dba80-d01e-11ea-857f-56f3b9045cda.png)

   Since `scope` is an attribute of `property` more than the property field of the mapping, I suggest
   adding the field 'scope' to `io.atlasmap.v2.Property`.  Then I can establish the proper elements when
   the property dialog is opened on an existing ADM.  I can't use `docId` for the scope value since it's needed
   to place the property field in the property doc within the UI.

   ref: error when attempting to send `scope` as a `property` attr:

`Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "scope" (class io.atlasmap.v2.Property), not marked as ignorable (3 known properties: "value", "name", "fieldType"])
 at [Source: (String)"{"AtlasMapping":{"jsonType":"io.atlasmap.v2.AtlasMapping","dataSource":[{"jsonType":"io.atlasmap.json.v2.JsonDataSource","id":"JSONSchemaSource","name":"JSONSchemaSource","description":"JSONSchemaSource","uri":"atlas:json:JSONSchemaSource","dataSourceType":"SOURCE"},{"jsonType":"io.atlasmap.json.v2.JsonDataSource","id":"JSONInstanceSource","name":"JSONInstanceSource","description":"JSONInstanceSource","uri":"atlas:json:JSONInstanceSource","dataSourceType":"TARGET","template":null}],"mappings":{""[truncated 910 chars]; line: 1, column: 1384] (through reference chain: io.atlasmap.v2.AtlasMapping["properties"]->io.atlasmap.v2.Properties["property"]->java.util.ArrayList[0]->io.atlasmap.v2.Property["scope"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.10.1.jar:2.10.1]`

**Closed** 2020-07-30 16:38 UTC
Labels: cat/enhancement, group/ui

**Comment by pleacu** [comment] 2021-03-12 13:48
![sc1](https://user-images.githubusercontent.com/2981421/110948778-c3f08500-830f-11eb-8962-f9408c1dc67e.png)
