### ISSUE TITLE
XSD issue with collection data type

### ISSUE THREAD

**Issue by Shrishti1234** [atlasmap/atlasmap#3584] opened 2021-12-16 05:02 UTC
**Describe the bug**
There is one issue with atlasmap 2.3.4 with XSD schema while mapping collection to collection. XSD schema shows correct datatype of GUI i.e. Collection but the mapping spec generated by XSD i.e atlasmapping-UI.0.json does not show that variable as Collection.
It creates an issue while transforming data.

**Attach .adm file and source document examples**
I am attaching on zip file while have following documents:
1. atlasmapping_XSD : Mapping file created  using XSD for transforming JSON to XML.
2. atlasmapping_Instance : Mapping file created using XML instance for transforming JSON to XML.
3. XSD_file : XSD file of XML instance
4. TargetDoc.xml : XML instance of target document.
5. XML_instance_output.xml : XML output using mapping spec created by XML instance.
6. XSD_schema_output.xml : XML output using mapping spec created by XSD.
  
**To Reproduce**

1. Import both mapping spec one by one on atlasmap GUI.
2. Check mapping in both adm file. It is same.
3. Transform data using XSD mapping spec and XML instance mapping spec.
4. Transformed result will be different

You can check the difference atlasmapping-UI.0.json file in .adm file. In XSD spec "member" variable does not show collection in
.json file.

**Expected behavior**
The result of both XSD and XML mapping spec should be same
[Atlasmap XSD issue.zip](https://github.com/atlasmap/atlasmap/files/7724673/Atlasmap.XSD.issue.zip)

**Comment by igarashitm** [comment] 2021-12-16 12:17
Duplicate of #3468

**Comment by igarashitm** [comment] 2021-12-16 12:18
It'll be backported to next 2.3.x release

**Closed by igarashitm** 2021-12-16 12:17 UTC
Labels: cat/bug, wontfix
