### ISSUE TITLE
[RFE] UI: Support importing kafka schema

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#3234] opened 2021-08-23 19:10 UTC
The 2nd option in https://github.com/atlasmap/atlasmap/discussions/3231#discussioncomment-1224009

Once #3233 is implemented, add an option to import a kafka schema as a Document in UI.

kafka-connect module at backend side has been implemented here:
https://github.com/atlasmap/atlasmap/tree/main/lib/modules/kafka-connect

Currently only JSON and AVRO are the supported Kafka Connect schema type.
https://github.com/atlasmap/atlasmap/blob/main/lib/modules/kafka-connect/service/src/main/java/io/atlasmap/kafkaconnect/service/KafkaConnectService.java#L117-L122

Note that Kafka Connect JSON schema is different from JSON schema.

There're a few examples of Kafka Connect JSON/AVRO schema here:
https://github.com/atlasmap/atlasmap/tree/main/lib/modules/kafka-connect/test-model/src/main/resources

Since Kafka Connect requires to put the schema along the data, Document metadata is required to run mapping for Kafka Connect Document. It expects `DataSourceMetadata.specification` to hold schema payload
https://github.com/atlasmap/atlasmap/blob/main/lib/modules/kafka-connect/module/src/main/java/io/atlasmap/kafkaconnect/module/KafkaConnectModule.java#L106
and the other inspection parameters to be in `DataSourceMetadata.inspectionParameters`
https://github.com/atlasmap/atlasmap/blob/main/lib/modules/kafka-connect/module/src/main/java/io/atlasmap/kafkaconnect/module/KafkaConnectModule.java#L108-L110
The required parameters are:
* schemaType - JSON or AVRO
* isKey - boolean flag, true for key, false for value

**Comment by pleacu** [comment] 2022-01-19 18:49
@igarashitm - so do you see user selecting the existing import document icon and then being presented with a select menu:
<pre>
* Import Kafka Aware Schema
* Import Standard Instance/ Schema
</pre>

Or do you see two separate icons on the panel - one for Kakka and one for standard?

**Comment by pleacu** [comment] 2022-01-19 19:23
Does the Kafka Connect AVRO schema have a specific suffix?

**Comment by igarashitm** [comment] 2022-01-19 19:24
Or Java class even could be migrated as an option if we can introduce dynamic form, like when Java class is selected, file selector is replaced with a textbox to enter a class name.

**Comment by igarashitm** [comment] 2022-01-19 19:25
> Does the Kafka Connect AVRO schema have a specific suffix?

it's `.json`, even the structure is very similar to Kafka Connect JSON

**Comment by igarashitm** [comment] 2022-01-19 19:27
Actually the file extension doesn't matter for those, user might use `.avro`, I don't know.

**Comment by igarashitm** [comment] 2022-01-19 19:32
And because those are all text file, IMO `.txt` should work for all the formats including JSON/XML schema/instance.

**Comment by pleacu** [comment] 2022-01-26 13:57
Hey @igarashitm - random question - can the import of Kafka Connect JSON/AVRO apply to bith Source and Target panels or Source only?

**Comment by igarashitm** [comment] 2022-01-26 13:59
It could be a Target Document as well.

**Comment by pleacu** [comment] 2022-01-26 18:52
@igarashitm - Hey Tomo - can you send me a suggestion on what the contract for AVRO and Kafka-JSON should appear like.  Looking at https://github.com/atlasmap/atlasmap/blob/main/ui/packages/atlasmap-core/src/contracts/documents/json.ts - I'm assuming it stays the same for Kafka Connect JSON schema but is the inspection type different?  I'm also assuming I'll need a new document contract for `avro.ts`.  Any clarity would help

**Comment by igarashitm** [comment] 2022-01-26 19:26
We need kafkaconnect.ts next to this json.ts. KafkaConnectInspectionRequest is here
https://github.com/atlasmap/atlasmap/blob/main/lib/modules/kafka-connect/model/src/main/java/io/atlasmap/kafkaconnect/v2/KafkaConnectInspectionRequest.java

And then `schemaType` in the inspection request option is one of `AVRO` or `JSON`. The kafka-connect schemas are different from anything else, and the inspection needs to be submitted to the kafka-connect module (`/v2/atlas/kafkaconnect`), not the JSON module (`/v2/atlas/json`).

**Comment by pleacu** [comment] 2022-01-28 20:52
Hey @igarashitm - so I've been banging my head on an issue.  Basically see:
https://github.com/atlasmap/atlasmap/blob/9e2b0c6dff8367c22cae79d1a52375fb24497a41/ui/packages/atlasmap/src/impl/AtlasmapProvider.tsx#L196
I've added:
 <pre>
      cfg.initCfg.baseKafkaConnectInspectionServiceUrl =
        baseKafkaConnectInspectionServiceUrl;
</pre>

I've also updated https://github.com/atlasmap/atlasmap/blob/9e2b0c6dff8367c22cae79d1a52375fb24497a41/ui/packages/atlasmap-standalone/src/index.tsx#L29

to add:
<pre>
    baseKafkaConnectInspectionServiceUrl={'/v2/atlas/kafkaconnect/'}
</pre>

The issue is `baseKafkaConnectInspectionServiceUrl` is always `undefined`'  The other base URLs have their proxy added:
<pre>
baseCSVInspectionServiceUrl: "http://localhost:8585/v2/atlas/csv/"
baseJSONInspectionServiceUrl: "http://localhost:8585/v2/atlas/json/"
baseJavaInspectionServiceUrl: "http://localhost:8585/v2/atlas/java/"
baseKafkaConnectInspectionServiceUrl: undefined
baseMappingServiceUrl: "http://localhost:8585/v2/atlas/"
baseXMLInspectionServiceUrl: "http://localhost:8585/v2/atlas/xml/"
</pre>

Do you know where those props are being modified??  It's passed the initial AtlasmapProvider render somewhere.  Best guess - I'll keep searching ... :)

**Comment by igarashitm** [comment] 2022-01-28 21:34
Did you add KafkaConnectInspectionModel in `ui/packages/atlasmap-core/src/models/inspect/`?

**Comment by pleacu** [comment] 2022-01-28 21:40
Yes - that's triggering the 
<pre>
Kafka Connect inspection service is not configured. Document will not be loaded: json-complex
</pre> 
error because the `cfg.initCfg.baseKafkaConnectInspectionServiceUrl` is `undefined`.  Somewhere between the standalone and AtlasmapProvider the IAtlasmapProvoer props are getting `http://localhost:8585` prepended to each base URL.  That's what I'm haing trouble finding.

**Comment by igarashitm** [comment] 2022-01-28 21:50
I would start from putting a breakpoint on ` cfg.initCfg.baseKafkaConnectInspectionServiceUrl = baseKafkaConnectInspectionServiceUrl;`

**Comment by pleacu** [comment] 2022-01-31 14:49
Hey @igarashitm - found my issue - `AtlasmapProvider.stories.tsx`.  I'm now getting 
<pre>
javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
	at io.atlasmap.kafkaconnect.service.KafkaConnectService.fromJson(KafkaConnectService.java:91) ~[atlas-kafka-connect-service-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at io.atlasmap.kafkaconnect.service.KafkaConnectService.inspect(KafkaConnectService.java:122) ~[atlas-kafka-connect-service-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
</pre>
I'm not sure where setting the `schemaType` to `AVRO/JSON` goes.  Can you take a quick look at:
https://github.com/pleacu/atlasmap/blob/i3234/ui/packages/atlasmap-core/src/contracts/documents/kafkaconnect.ts
https://github.com/pleacu/atlasmap/blob/i3234/ui/packages/atlasmap-core/src/models/inspect/kafkaconnect-inspection.model.ts

**Comment by pleacu** [comment] 2022-01-31 15:51
Tried this:
<pre>
export class KafkaConnectInspectionRequestModel extends DocumentInspectionRequestModel {
  url = this.cfg.initCfg.baseKafkaConnectInspectionServiceUrl + 'inspect';
  options = new KafkaConnectInspectionRequestOptions(this.cfg, this.doc);
}

export class KafkaConnectInspectionRequestOptions extends DocumentInspectionRequestOptions {
  constructor(protected cfg: ConfigModel, protected doc: DocumentDefinition) {
    super(cfg, doc);
    const kafkaconnect = {
      KafkaConnectInspectionRequest: {
        jsonType: KAFKACONNECT_INSPECTION_REQUEST_JSON_TYPE,
        type: this.doc.inspectionType,
        jsonData: this.doc.inspectionSource,
        inspectPaths: this.doc.inspectionPaths,
      },
    };
    this.json = kafkaconnect;
  }
}
</pre>
Same result.  Still not sure where the `schemaType` gets passed.

**Comment by igarashitm** [comment] 2022-01-31 16:05
The `KafkaConnectInspectionRequest` has an `options` property which is a Map.
https://github.com/atlasmap/atlasmap/blob/main/lib/modules/kafka-connect/model/src/main/java/io/atlasmap/kafkaconnect/v2/KafkaConnectInspectionRequest.java#L47

You can put the schema type In that map with `schemaType` as a key.

Did you get any `caused by` at the backend? `KafkaConnectService.fromJson(KafkaConnectService.java:91)` shows that it failed to  deserialize the request payload, but what was wrong should be in the `caused by`.

**Comment by pleacu** [comment] 2022-01-31 16:23
Yup - it was:
<pre>
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "type" (class io.atlasmap.kafkaconnect.v2.KafkaConnectInspectionRequest), not marked as ignorable (6 known properties: "namespaceExclusions", "fieldNameExclusions", "schemaData", "uri", "options", "typeNameExclusions"])
 at [Source: (io.undertow.servlet.spec.ServletInputStreamImpl); line: 1, column: 114] (through reference chain: io.atlasmap.kafkaconnect.v2.KafkaConnectInspectionRequest["type"])
</pre>

**Comment by pleacu** [comment] 2022-02-04 16:18
Hey @igarashitm - I've got the kafka connect doc support mostly working.  The issue I'm having is with `avro-primitive.json`.  The JSON response I'm getting from the runtime's Kafka JSON primitive inspection does not include the field name:
<pre>
responseJson:
KafkaConnectInspectionResponse:
executionTime: 26
jsonType: "io.atlasmap.kafkaconnect.v2.KafkaConnectInspectionResponse"
kafkaConnectDocument:
enumeration: false
fieldType: "STRING"
fields: {field: Array(0)}
jsonType: "io.atlasmap.kafkaconnect.v2.KafkaConnectDocument"
path: "/"
rootSchemaType: "STRING"
__proto__: Object
__proto__: Object
__proto__: Object
</pre>
It's missing `name: str` to correspond to the JSON file:
<pre>
{
  "type": "string",
  "name": "str"
}
</pre>
Here is the result of inspecting the `json-primitive.json`
<pre>
{
  "name": "primitive",
  "type": "string"
}
</pre>
Ok response:
<pre>
responseJson:
KafkaConnectInspectionResponse:
executionTime: 26
jsonType: "io.atlasmap.kafkaconnect.v2.KafkaConnectInspectionResponse"
kafkaConnectDocument:
enumeration: false
fieldType: "STRING"
fields: {field: Array(0)}
jsonType: "io.atlasmap.kafkaconnect.v2.KafkaConnectDocument"
name: "primitive"
path: "/"
rootSchemaType: "STRING"
__proto__: Object
__proto__: Object

</pre>

![sc1](https://user-images.githubusercontent.com/2981421/152563995-654c1c39-ff5f-40bf-929f-641ccfcca143.png)

**Comment by igarashitm** [comment] 2022-02-04 16:46
This is a primitive document, where the document itself is a primitive field and it has `/` as its field path. We can skip it at this moment - I think we haven't ever considered about supporting primitive document in UI. Note that it doesn't have a field name to have `/` as a path, as if it has a field name `fieldName`, then the path has to be `/fieldName`, which is a sub field of the Document but different from the primitive Document.

**Comment by igarashitm** [comment] 2022-02-04 16:50
cf. https://github.com/atlasmap/atlasmap/issues/9

**Comment by igarashitm** [comment] 2022-02-04 16:51
Maybe it could be displayed as `/` just like we do for topmost collection?

**Comment by pleacu** [comment] 2022-02-04 17:30
Ok - so then the `json-primitive.json` document which does have a name  field should *not* be displayed and in both cases it should just display `/<>` - is that correct? or should we keep displaying `primitive` and the field name for the kafka-json primitive example and `/<>` for the avro example?

**Comment by igarashitm** [comment] 2022-02-04 17:34
Nope, it should be `/`, not `/<>`. It's not a collection.
Maybe better to get the field name empty for the primitive Document in the inspection result. I'll take care of it.

**Comment by igarashitm** [comment] 2022-02-04 17:53
Wait... this difference comes from apicurio-registry so we'll be better to keep the inspection as-is. Let's just ignore the field name in UI and show it as `/` if it's a primitive Document.

**Comment by pleacu** [comment] 2022-02-04 18:56
ok - this is what I've got now:

![sc2](https://user-images.githubusercontent.com/2981421/152586832-90594d1d-bfac-4eb1-81e5-cbc629e16aba.png)

**Closed** 2022-02-09 00:33 UTC
Labels: group/ui, cat/enhancement
