### ISSUE TITLE
[RFE] Removing structure from transformed response on basis of some condition

### ISSUE THREAD

**Issue by Shrishti1234** [atlasmap/atlasmap#3681] opened 2022-01-19 03:46 UTC
**Is your feature request related to a problem? Please describe.**
I have a requirement of removing a structure from transformed response if some paramter is not in input request i.e. for source doc.

**Describe the solution you'd like**
This is the screenshot of mapping which I need to do for my use case.
![image](https://user-images.githubusercontent.com/39737814/150059284-2789f03d-955b-4be3-8fff-8667ccfe6474.png)

On above screenshot there are two source document 1. SampleEoc( JSON request which we expect from client) 2. RemoveSample(Default Json which I saved internally and while using atlasmap  saved this request to sourceMap).
**I have done this because some values are hardcoded for my transformed JSON**.
this is SampleEoc JSON request :
{
	"resources": [
		{
			"name": "IMSI",
			"value": "6267171"
		},
		{
			"name": "KiValue",
			"value": "6267171"
		},
		{
			"name": "MSISDN",
			"value": "6267171"
		}
	]
}
This is RemoveSample JSON request(Default JSON):
{
	"resources": [
		{
			"resourceSpecification": "SIM",
			"resourceType": "PhysicalResourceSpec"
		},
		{
			"resourceSpecification": "MSISDN",
			"resourceType": "LogicalResourceSpec"
		}
	]
}
Now I want to achieve If in SampleEOC JSON request "MSISDN" field is not coming then remove 
{
			"resourceSpecification": "MSISDN",
			"resourceType": "LogicalResourceSpec"
}
this structure from transformed JSON.
if MSISDN is not present in name field of SampleEOC then remove "resourceSpecification": "MSISDN", structure from transformed JSON.
Is there anyway currently to do this thing?

**Comment by igarashitm** [comment] 2022-01-19 16:23
You could use the conditional mapping expression if it's in a same collection, like `IF(SampleEOC:/resources/name == 'MSISDN', SampleEOC:/resources/resourceSpecification, null)`, but it doesn't work for the 2 separated source documents. You'd need to wait for https://github.com/atlasmap/atlasmap/issues/1514 and write your own logic.

**Comment by igarashitm** [comment] 2022-01-19 16:26
Duplicate of #1514

**Closed by igarashitm** 2022-01-19 16:26 UTC
Labels: cat/enhancement, needmoreinfo
