### ISSUE TITLE
Could not find document for mapped field 'xxx' at URI atlas:json:sample when using Mapping preview with two datasources of different kind but with same name

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#2150] opened 2020-06-03 10:06 UTC
- import a sample.xml as source
- import a sample.json as target
- map one field to the other
- activate mapping preview
- type in the mapping preview field
--> there is an "internal" error popup

![Screenshot from 2020-06-03 12-03-49](https://user-images.githubusercontent.com/1105127/83624229-a200ef80-a592-11ea-8af2-e568080e72b9.png)

tested with 2.0.3 on Chrome

this looks very similar to https://github.com/atlasmap/atlasmap/issues/1710

**Comment by apupier** [comment] 2021-01-26 13:29
reported also By Bruno: https://issues.redhat.com/browse/FUSETOOLS2-955

**Comment by igarashitm** [comment] 2021-04-22 14:24
Duplicate of #2198

**Closed by igarashitm** 2021-04-22 14:24 UTC
