### ISSUE TITLE
[Datamapper] Transformation's delimiter not saved

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#827] opened 2019-03-13 15:00 UTC
_From @avano on March 13, 2019 13:26_

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Integration sql -> datamapper -> amq

```
1. open datamapper
2. map from one field to another
3. add source transformation
4. select concatenate
5. insert delimiter ,
6. click done
7. reopen datamapper to check the delimiter
8. comma isn't there
9. (bonus) there are now 2 concatenate transformations with empty delimiters, writing into one mirrors the input in the second
```

_Copied from original issue: syndesisio/syndesis#4874_

**Comment by igarashitm** [comment] 2019-03-13 15:00
_From @heiko-braun on March 13, 2019 14:43_

@igarashitm Is this an AtlasMap issue?

**Comment by igarashitm** [comment] 2019-03-13 15:00
Yes highly possibly, moving to atlasmap repo

**Comment by igarashitm** [comment] 2019-03-18 15:24
@avano is this still an issue or just confused by syndesisio/syndesis#4868 ? I verified it is properly restored in standalone UI.

**Comment by avano** [comment] 2019-03-18 15:56
@igarashitm those are two separate issues

**Comment by avano** [comment] 2019-03-18 16:12
I just retried with latest syndesis master and still can see it

**Comment by avano** [comment] 2019-03-18 16:27
@igarashitm if I do the steps slowly, then sometimes the delimiter is saved, so probably the culprit is the same as https://github.com/syndesisio/syndesis/issues/4840 

however it seems the delimiter field is duplicated every time:

![out](https://user-images.githubusercontent.com/7081216/54546011-1efe7400-49a3-11e9-9e2e-32da9d473605.gif)

**Comment by igarashitm** [comment] 2019-03-18 18:09
Hmm that duplicated transformation looks like a separate issue, and I haven't seen it in standalone. There must be some condition to reproduce it.

**Comment by igarashitm** [comment] 2019-03-18 23:54
Both of them reproduced in Syndesis. Need deeper investigation to get to the root.

**Comment by igarashitm** [comment] 2019-03-19 21:42
This delimiter not saved issue specifically comes from that there's no way to grab it unless user emits some browser event, like move the focus out from input field. In order to fix this, we'll need to have a callback from Syndesis `Done` button.

**Comment by igarashitm** [comment] 2019-03-20 11:25
A workaround for this is to focus out from input field after enter the delimiter. The `onBlur` event on the input field triggers save mappings, and the delimiter is reflected to the saved mappings.

Since there's a workaround, I would say this is p1.

**Comment by pleacu** [comment] 2019-03-20 19:16
@gashcrumb @igarashitm @heiko-braun - you guys all seem interested...

Hey - I think I've got a fix for the missing concatenate transformation delimiter.  The issue is that if you're still in the delimiter input text field at the time you click 'Done' it isn't saved before AtlasMap is closed.  The fix is to call the AtlasMap mapping service to save the current mapping within the SaveMappingHandler:

`--- a/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
+++ b/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
@@ -381,7 +381,8 @@ export class DataMapperHostComponent implements OnInit, OnDestroy {
     //subscribe to mapping save callback from data mapper
     return this.cfg.mappingService.saveMappingOutput$
       .pipe(debounceTime(500))
-      .subscribe((saveHandler: Function) => {
+      .subscribe(async(saveHandler: Function) => {
+        await this.cfg.mappingService.saveCurrentMapping();
         const json = this.cfg.mappingService.serializeMappingsToJSON();
         this.mappings.emit(JSON.stringify(json));
         this.cfg.mappingService.handleMappingSaveSuccess(saveHandler);
`
I consistently see the delimiter with this fix (the delim is duplicated because of https://github.com/atlasmap/atlasmap/issues/834) - Should I copy this issue back to the Syndesis issue queue and gen a PR?

**Comment by gashcrumb** [comment] 2019-03-20 19:22
@pleacu Looks good to me, we can go with that, thanks!

**Comment by igarashitm** [comment] 2019-03-20 19:22
+1
I think we can reuse syndesisio/syndesis#4874

**Comment by pleacu** [comment] 2019-03-21 13:15
Fixed in Syndesis:

https://github.com/syndesisio/syndesis/issues/4874

**Closed by pleacu** 2019-03-21 13:15 UTC
Labels: cat/bug, group/ui, prio/p1, source/qe
