### ISSUE TITLE
 Conditional mapping support for collection field.

### ISSUE THREAD

**Issue by aravind1227** [atlasmap/atlasmap#1613] opened 2019-12-18 13:41 UTC
Hi There,

UI shows an waring "Cannot establish a conditional mapping expression when referencing a source collection field." while try to wite a condition on collection filed. this would be a common requirement to add contions on collection field, is there a way to achive it ?

**Comment by igarashitm** [comment] 2019-12-18 15:38
Duplicate of #1185 
We're working on it, so please stay tuned.

**Closed by igarashitm** 2019-12-18 15:38 UTC
Labels: notif/triage
