### ISSUE TITLE
Duplicate Enum non selectable on load

### ISSUE THREAD

**Issue by ronMilne** [atlasmap/atlasmap#3196] opened 2021-08-12 20:35 UTC
The attached screenshot shows that once you have two enums in different types it becomes unavailable. As orgStatus is declared in the outer object - the inner object (organization) that contains the same enum is no longer available.

![duplicate enum grayed on load](https://user-images.githubusercontent.com/24907744/129265964-e0d2d29e-c2d1-4570-b77a-be17d6c79220.png)

**Comment by ronMilne** [comment] 2021-08-12 20:44
The following Jar was loaded in the UI (renamed to zip for upload) version 2.2.1
[searchNniName-model.zip](https://github.com/atlasmap/atlasmap/files/6978468/searchNniName-model.zip)

**Comment by igarashitm** [comment] 2021-08-20 17:29
Can you upload ADM file?

**Comment by igarashitm** [comment] 2021-08-23 15:00
This would need to wait for #579

**Comment by igarashitm** [comment] 2021-08-23 15:00
Duplicate of #255

**Closed by igarashitm** 2021-08-23 15:00 UTC
Labels: cat/bug
