### ISSUE TITLE
 Could not find field action definition for action 'Split'  

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#1252] opened 2019-10-01 15:11 UTC
![screenshot_20191001_163923](https://user-images.githubusercontent.com/6814482/65974972-2c2a0e80-e46e-11e9-880e-cb6ec1ef9a5a.png)

this occurs when there is split in integration and some bath update for example:
DB - > Split -> Datamaper -> DB(Batch update) 

Step to reproduce: create mentioned integration and publish. 
Edit the integration
exported integration:
[asdf-export.zip](https://github.com/atlasmap/atlasmap/files/3677054/asdf-export.zip)

**Comment by igarashitm** [comment] 2019-10-01 15:38
This looks like a duplicate of #1235 reported in a comment in issues.jboss.org/browse/ENTESB-11691 - should have been fixed in 1.42.4.

**Comment by igarashitm** [comment] 2019-10-01 17:54
![Screenshot from 2019-10-01 13-51-37](https://user-images.githubusercontent.com/265462/65986954-e7dd4500-e452-11e9-8ac3-e2b752ba637d.png)
This is the expected behavior for one-to-many where target is a collection I can see with upstream master.

**Closed** 2019-10-02 14:54 UTC
Labels: cat/bug, notif/triage, source/qe, wontfix
