### ISSUE TITLE
[RFE] Support external $ref for JSON schema

### ISSUE THREAD

**Issue by pandora2333** [atlasmap/atlasmap#3679] opened 2022-01-18 12:58 UTC
**Is your feature request related to a problem? Please describe.**
Import a Json Schema with $ref syntax, it's not supported at present

**Attach .adm file and source document examples if you are looking at specific current behavior**
```json
{
  "$id": "https://example.com/schemas/customer",
    "type": "object",
    "properties": {
      "first_name": { "type": "string" },
      "last_name": { "type": "string" },
      "shipping_address": { "$ref": "/schemas/address" },
      "billing_address": { "$ref": "/schemas/address" }
    },
  "required": ["first_name", "last_name", "shipping_address", "billing_address"]
}
```

**Describe the solution you'd like**
Subsequent versions can support for JSON schema ref syntax

**Comment by igarashitm** [comment] 2022-01-19 19:12
Duplicate of #3129

**Closed by igarashitm** 2022-01-19 19:12 UTC
Labels: group/runtime, cat/enhancement
