### ISSUE TITLE
Does AtlasMap supports automatic mapping if key is same on both source & target

### ISSUE THREAD

**Issue by gurumurthy-godlaveeti** [atlasmap/atlasmap#4141] opened 2022-06-30 09:03 UTC
### Discussed in https://github.com/atlasmap/atlasmap/discussions/4140

<div type='discussions-op-text'>

<sup>Originally posted by **gurumurthy-godlaveeti** June 30, 2022</sup>
Hi,

I would like to see if any possibility to have default mapping for all fields having same name & structure on both source & target sides.

For example, messageHeader is same in both source & target as per below screenshot so can it have automatic mapping?
![image](https://user-images.githubusercontent.com/101185013/176636613-f57b4c7e-bf73-45f4-9437-3b2980bd9a58.png)
</div>

**Comment by gurumurthy-godlaveeti** [comment] 2022-06-30 09:04
Hi @rhuss , @chirino , @christophd , @WillemJiang ,

Could you please check this & help to understand it.

**Comment by igarashitm** [comment] 2022-06-30 12:38
Duplicate of #86

**Closed by igarashitm** 2022-06-30 12:38 UTC
