### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by muratyildiz1976** [atlasmap/atlasmap#3939] opened 2022-04-12 19:59 UTC
**description**
AtlasMap Data Mapper UI v2.3.17 (standalone) displays in some cases complex types as simple types and disabled

**environment**
Microsoft Edge Version 100.0.1185.36 (Offizielles Build) (64-Bit)
Windows 10
Java 8 (xjc) 
AtlasMap Data Mapper UI v2.3.17

 **reproduction**
1) unzip flatten.zip
2) cd flatten/out
3) xjc -d ./ -catalog ../catalog.cat ../xbau-nachrichten-baugenehmigung.xsd
4) find ./ -name "*.java" > sources.txt
5) javac -cp ./ -d ./ @sources.txt -Xlint:unchecked
6) find ./ -name "*.java" -type f -delete
7) jar cvf ./antrag200.jar ./de/*./net/*
8) AtlasMap Data Mapper UI -> import a java archive  in 
9) select the antrag200.jar
10) AtlasMap Data Mapper UI -> Load Java Document From Custom Class
11) then select custom class name "de.xleitstell.xbau._2._3.BaugenehmigungAntrag0200"
12) expand some elments 
13) you will see the misbehavior like in description

**expected behavior**
- complex types are displayed with directory icon and can be expanded and are not in disabled color

**zip attachment**
[flatten.zip](https://github.com/atlasmap/atlasmap/files/8476129/flatten.zip)

**screenshot**

![bug](https://user-images.githubusercontent.com/968510/163044727-9e7eeb43-a364-41cb-9839-828c6b663bd2.png)

**Comment by igarashitm** [comment] 2022-04-12 20:10
Duplicate of #255

**Closed by igarashitm** 2022-04-12 20:10 UTC
Labels: cat/bug

**Comment by muratyildiz1976** [comment] 2022-04-12 22:26
Is there than a workaround to map those fields ?
