### ISSUE TITLE
Preview error when consuming complex collection

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2607] opened 2021-03-17 17:18 UTC
Although preview doesn't support collection field yet because there's no way to input multiple values (#501), it still should work as if it's non-collection (single value).
Using this schema https://github.com/atlasmap/atlasmap/blob/master/ui/test-resources/json/schema/JSONSchemaSource.json

![Screenshot from 2021-03-17 13-15-40](https://user-images.githubusercontent.com/265462/111509391-10c6c800-8723-11eb-94ae-90ffb91a559a.png)

Due to a bug in preview context

**Comment by igarashitm** [comment] 2021-03-17 21:54
@pleacu could UI put one more layer for the complex collection field when it's sent for preview? Currently it's
```json
  "inputFieldGroup": {
    "jsonType": "io.atlasmap.v2.FieldGroup",
    "actions": [],
    "docId": "JSONSchemaSource-8a461369-fa0e-411f-bd9a-ce16dcb17ca9",
    "path": "/addressList<>",
    "fieldType": "COMPLEX",
    "field": [
      {
        "jsonType": "io.atlasmap.json.v2.JsonField",
        "value": "Boston",
        "docId": "JSONSchemaSource-8a461369-fa0e-411f-bd9a-ce16dcb17ca9",
        "path": "/addressList<>/city",
        "fieldType": "STRING",
        "name": "city",
        "userCreated": false
      },
      {
        "jsonType": "io.atlasmap.json.v2.JsonField",
        "value": "MA",
        "docId": "JSONSchemaSource-8a461369-fa0e-411f-bd9a-ce16dcb17ca9",
        "path": "/addressList<>/state",
        "fieldType": "STRING",
        "name": "state",
        "userCreated": false
      }
    ]
  }
```

But in order to express collection instance, it needs to be like this, note that `/addressList<0>` field group is added in the middle
```json
  "inputFieldGroup": {
    "jsonType": "io.atlasmap.v2.FieldGroup",
    "actions": [],
    "docId": "JSONSchemaSource-8a461369-fa0e-411f-bd9a-ce16dcb17ca9",
    "path": "/addressList<>",
    "fieldType": "COMPLEX",
    "field": [
      {
      "jsonType": "io.atlasmap.v2.FieldGroup",
      "actions": [],
      "docId": "JSONSchemaSource-8a461369-fa0e-411f-bd9a-ce16dcb17ca9",
      "path": "/addressList<0>",
      "fieldType": "COMPLEX",
      "field": [
        {
          "jsonType": "io.atlasmap.json.v2.JsonField",
          "value": "Boston",
          "docId": "JSONSchemaSource-8a461369-fa0e-411f-bd9a-ce16dcb17ca9",
          "path": "/addressList<0>/city",
          "fieldType": "STRING",
          "name": "city",
          "userCreated": false
        },
        {
          "jsonType": "io.atlasmap.json.v2.JsonField",
          "value": "MA",
          "docId": "JSONSchemaSource-8a461369-fa0e-411f-bd9a-ce16dcb17ca9",
          "path": "/addressList<0>/state",
          "fieldType": "STRING",
          "name": "state",
          "userCreated": false
        }
      ]
    }
    ]
  }
```
In this way, #501 will be just a matter of adding multiple collection instances. We already handle collections in this way at runtime.

**Comment by igarashitm** [comment] 2021-03-18 12:32
Changed to `enhancement` - this is a temporary&limited fix while collection is not supported for preview officially yet.

**Comment by pleacu** [comment] 2021-03-18 12:36
I'll take this on as soon as I'm done with the expression enum UI dropdown.  That one will need server work but I can push the UI side when it's ready.

**Comment by igarashitm** [comment] 2021-03-22 14:28
We still expect to have UI change, see https://github.com/atlasmap/atlasmap/issues/2607#issuecomment-801468019

**Comment by pleacu** [comment] 2021-03-29 14:50
@igarashitm - so with the updated mapping - you have two fields that are part of the same complex parent (`addressList`).  What if I have a mixture of complex and non-complex fields in the mapping?  Do I need to walk all mapped fields to determine which fields belong to which complex parent?  Can I have something like:

`inputFieldGroup`
  `complex field`
    `field`
  'complex field`
    `field`
  'field`

where if a field is part of an array or list I just  generate a complex field ahead of it (i.e. not attempting to capture all of the mapped fields that belong to a particular complex field at once).
wdyt?

**Comment by igarashitm** [comment] 2021-03-29 14:57
Basically runtime just want what is used in the expression, so if a COMPLEX field is used in expression, that is needed with children filled. Otherwise the terminal field alone has to be there. If the field used in expression is wrapped with parent COMPLEX field, currently runtime can't dig it out.

**Comment by pleacu** [comment] 2021-03-29 17:37
That might explain what I'm seeing now.  So - With a simple tweak I'm able to generate this for your example:

    "mapping" : {
      "jsonType" : "io.atlasmap.v2.Mapping",
      "expression" : "select( filter( ${JSONSchemaSource-8f333f3e-724a-411d-8c33-8d4b4d94ccba:/addressList<>} ,  ${/city} != 'Boston'),  ${/state})",
      "inputFieldGroup" : {
        "jsonType" : "io.atlasmap.v2.FieldGroup",
        "actions" : [ ],
        "field" : [ {
          "jsonType" : "io.atlasmap.v2.FieldGroup",
          "actions" : [ ],
          "docId" : "JSONSchemaSource-8f333f3e-724a-411d-8c33-8d4b4d94ccba",
          "path" : "/addressList<>",
          "fieldType" : "COMPLEX",
          "field" : [ {
            "jsonType" : "io.atlasmap.json.v2.JsonField",
            "value" : "Boston",
            "docId" : "JSONSchemaSource-8f333f3e-724a-411d-8c33-8d4b4d94ccba",
            "path" : "/addressList<>/city",
            "fieldType" : "STRING",
            "name" : "city"
          } ]
        }, {
          "jsonType" : "io.atlasmap.v2.FieldGroup",
          "actions" : [ ],
          "docId" : "JSONSchemaSource-8f333f3e-724a-411d-8c33-8d4b4d94ccba",
          "path" : "/addressList<>",
          "fieldType" : "COMPLEX",
          "field" : [ {
            "jsonType" : "io.atlasmap.json.v2.JsonField",
            "value" : "MA",
            "docId" : "JSONSchemaSource-8f333f3e-724a-411d-8c33-8d4b4d94ccba",
            "path" : "/addressList<>/state",
            "fieldType" : "STRING",
            "name" : "state"
          } ]
        } ]
      },
      "inputField" : [ ],
      "outputField" : [ {
        "jsonType" : "io.atlasmap.json.v2.JsonField",
        "docId" : "JSONSchemaSource-de4e6257-407e-4bfb-a630-e7c3559b9603",
        "path" : "/addressList<>/city",
        "fieldType" : "STRING",
        "name" : "city"
      } ],
      "id" : "preview"
    },
    "audits" : {
      "audit" : [ {
        "message" : "Expression processing error: null",
        "path" : "select( filter( ${JSONSchemaSource-8f333f3e-724a-411d-8c33-8d4b4d94ccba:/addressList<>} ,  ${/city} != 'Boston'),  ${/state})",
        "status" : "ERROR"
      } ]

I generate a separate  complex input field group for each source-side field.  The audit shows a null reference.  If this is because the `COMPLEX` field doesn't accept values should we just close this issue and tackle it as part of #501

**Comment by igarashitm** [comment] 2021-03-29 17:43
Please see https://github.com/atlasmap/atlasmap/issues/2607#issuecomment-801468019 - this issue is to consume a terminal field in a collection, but not an expression consuming COMPLEX field itself. In order to achieve it, we need a collection instance in field hierarchy. Note that the middle field has `/addressList<0>/city`.

**Comment by igarashitm** [comment] 2021-03-29 17:58
So yeah, in this example it does consume a COMPLEX field in an expression. Then it has to have only one `/addressList` field as a top level field so that expression processor can retrieve it. All fields that is referred from expression has to be a top level field (it's fine to be wrapped with anonymous FieldGroup). Duplicated `/addressList` shown in https://github.com/atlasmap/atlasmap/issues/2607#issuecomment-809573750 won't work.

**Comment by pleacu** [comment] 2021-03-30 18:04
@igarashitm - Hey Tomo - so here's my latest.  The outermost `inputFieldGroup` is for the many-to-one mapping so it does not contain `docId` or `path`.  It's followed by an `addressList<>` field group, then the instance `addressList<0>` field group and then the two fields for `city` and `state`.

<pre><font color="#1E8C32">2021-03-30 13:41:33.994 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">15479</font> --- [  XNIO-1 task-1] <font color="#06989A">io.atlasmap.service.AtlasService        </font> : Preview outcome: {
  &quot;ProcessMappingResponse&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.ProcessMappingResponse&quot;,
    &quot;mapping&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
      &quot;expression&quot; : &quot;if (select( filter(${JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d:/addressList&lt;&gt;} , ${/city} != &apos;Boston&apos;), ${/state})&quot;,
      &quot;inputFieldGroup&quot; : {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;docId&quot; : &quot;JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;&quot;,
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
            &quot;actions&quot; : [ ],
            &quot;docId&quot; : &quot;JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d&quot;,
            &quot;path&quot; : &quot;/addressList&lt;0&gt;&quot;,
            &quot;fieldType&quot; : &quot;COMPLEX&quot;,
            &quot;field&quot; : [ {
              &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
              &quot;value&quot; : &quot;x&quot;,
              &quot;docId&quot; : &quot;JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d&quot;,
              &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
              &quot;fieldType&quot; : &quot;STRING&quot;,
              &quot;name&quot; : &quot;city&quot;
            }, {
              &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
              &quot;value&quot; : &quot;y&quot;,
              &quot;docId&quot; : &quot;JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d&quot;,
              &quot;path&quot; : &quot;/addressList&lt;&gt;/state&quot;,
              &quot;fieldType&quot; : &quot;STRING&quot;,
              &quot;name&quot; : &quot;state&quot;
            } ]
          } ]
        } ]
      },
      &quot;inputField&quot; : [ ],
      &quot;outputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
        &quot;docId&quot; : &quot;JSONSchemaSource-ae6eae36-18ca-42e2-a2be-be5518c663b6&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;,
        &quot;name&quot; : &quot;city&quot;
      } ],
      &quot;id&quot; : &quot;preview&quot;
    },
    &quot;audits&quot; : {
      &quot;audit&quot; : [ {
        &quot;message&quot; : &quot;Expression processing error [if (select( filter(${JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d:/addressList&lt;&gt;} , ${/city} != &apos;Boston&apos;), ${/state})]: if (select( filter(${JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d:/addressList&lt;&gt;} , ${/city} != &apos;Boston&apos;), ${/state})&quot;,
        &quot;docId&quot; : &quot;if (select( filter(${JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d:/addressList&lt;&gt;} , ${/city} != &apos;Boston&apos;), ${/state})&quot;,
        &quot;docName&quot; : &quot;Preview&quot;,
        &quot;status&quot; : &quot;ERROR&quot;
      } ]
    }
  }
</pre>

I am getting a tb from the server:

<pre><font color="#1E8C32">2021-03-30 13:41:33.993 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">15479</font> --- [  XNIO-1 task-1] <font color="#06989A">i.a.c.DefaultAtlasExpressionProcessor   </font> : 

io.atlasmap.expression.ExpressionException: if (select( filter(${JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d:/addressList&lt;&gt;} , ${/city} != &apos;Boston&apos;), ${/state})
	at io.atlasmap.expression.Expression.parse(Expression.java:67) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasExpressionProcessor.processExpression(DefaultAtlasExpressionProcessor.java:59) ~[atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasContext.processSourceFieldMapping(DefaultAtlasContext.java:399) [atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.core.DefaultAtlasPreviewContext.processPreview(DefaultAtlasPreviewContext.java:93) [atlas-core-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.service.AtlasService.processMappingRequest(AtlasService.java:554) [atlas-service-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
</pre>

...

<pre>Caused by: io.atlasmap.expression.parser.ParseException: Parse error at line 1, column 126.  Encountered: &lt;EOF&gt;
	at io.atlasmap.expression.parser.Parser.generateParseException(Parser.java:990) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.expression.parser.Parser.jj_consume_token(Parser.java:938) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.expression.parser.Parser.functionExpr(Parser.java:370) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.expression.parser.Parser.primaryExpr(Parser.java:318) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.expression.parser.Parser.unaryExpr(Parser.java:284) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.expression.parser.Parser.multExpr(Parser.java:217) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.expression.parser.Parser.addExpression(Parser.java:186) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.expression.parser.Parser.comparisonExpression(Parser.java:134) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.expression.parser.Parser.equalityExpression(Parser.java:95) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.expression.parser.Parser.andExpression(Parser.java:74) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.expression.parser.Parser.orExpression(Parser.java:53) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.expression.parser.Parser.parse(Parser.java:44) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
	at io.atlasmap.expression.Expression.parse(Expression.java:63) ~[atlas-expression-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
</pre>

I've also tried with just the two field groups (no outer `addressList<>`, `addressList<0>` field group and then the two fields for `city` and `state`):

<pre><font color="#1E8C32">2021-03-30 13:32:09.184 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">15479</font> --- [  XNIO-1 task-1] <font color="#06989A">io.atlasmap.service.AtlasService        </font> : Preview outcome: {
  &quot;ProcessMappingResponse&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.ProcessMappingResponse&quot;,
    &quot;mapping&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
      &quot;expression&quot; : &quot;if (select( filter(${JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d:/addressList&lt;&gt;} , ${/city} != &apos;Boston&apos;), ${/state})&quot;,
      &quot;inputFieldGroup&quot; : {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;docId&quot; : &quot;JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d&quot;,
          &quot;path&quot; : &quot;/addressList&lt;0&gt;&quot;,
          &quot;fieldType&quot; : &quot;COMPLEX&quot;,
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;value&quot; : &quot;x&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;city&quot;
          }, {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;value&quot; : &quot;y&quot;,
            &quot;docId&quot; : &quot;JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d&quot;,
            &quot;path&quot; : &quot;/addressList&lt;&gt;/state&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;state&quot;
          } ]
        } ]
      },
      &quot;inputField&quot; : [ ],
      &quot;outputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
        &quot;docId&quot; : &quot;JSONSchemaSource-ae6eae36-18ca-42e2-a2be-be5518c663b6&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;,
        &quot;name&quot; : &quot;city&quot;
      } ],
      &quot;id&quot; : &quot;preview&quot;
    },
    &quot;audits&quot; : {
      &quot;audit&quot; : [ {
        &quot;message&quot; : &quot;Expression processing error [if (select( filter(${JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d:/addressList&lt;&gt;} , ${/city} != &apos;Boston&apos;), ${/state})]: if (select( filter(${JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d:/addressList&lt;&gt;} , ${/city} != &apos;Boston&apos;), ${/state})&quot;,
        &quot;docId&quot; : &quot;if (select( filter(${JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d:/addressList&lt;&gt;} , ${/city} != &apos;Boston&apos;), ${/state})&quot;,
        &quot;docName&quot; : &quot;Preview&quot;,
        &quot;status&quot; : &quot;ERROR&quot;
      } ]
    }
  }
</pre>

The audit `docId` field looks corrupted as well.

wdyt?

**Comment by igarashitm** [comment] 2021-03-30 18:07
The expression looks invalid, it has 3 `(` but only 2 `)` - I guess the first `if (` is a typo.

**Comment by igarashitm** [comment] 2021-03-30 18:11
Also, the top FieldGroup `/addressList<>` is missing, like it's shown in  https://github.com/atlasmap/atlasmap/issues/2607#issuecomment-801468019 , `/addressList<0>` needs a parent `/addressList<>`. In future we  supports multiple instances of collection, then the parent `/addressList<>` FieldGroup will hold multiple `/addressList<n>` field.

**Comment by igarashitm** [comment] 2021-03-30 18:13
And the `/addressList<>/city` also needs collection index if it's under indexed collection, i.e. `/addressList<0>/city`.

**Comment by igarashitm** [comment] 2021-03-30 18:21
The docId in the Audit is used to indicate which Document the problematic field belongs to, but I put an expression instead in case it uses expression as expression could use fields from multiple documents and doesn't make sense showing one of them.

**Comment by pleacu** [comment] 2021-03-30 18:29
Good catch @igarashitm - removing the `if (` appears to fix the issue!  Ok - this works:

<pre><font color="#1E8C32">2021-03-30 14:24:54.083 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">15479</font> --- [  XNIO-1 task-2] <font color="#06989A">io.atlasmap.service.AtlasService        </font> : Preview outcome: {
  &quot;ProcessMappingResponse&quot; : {
    &quot;jsonType&quot; : &quot;io.atlasmap.v2.ProcessMappingResponse&quot;,
    &quot;mapping&quot; : {
      &quot;jsonType&quot; : &quot;io.atlasmap.v2.Mapping&quot;,
      &quot;expression&quot; : &quot;select( filter(${JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d:/addressList&lt;&gt;} , ${/city} != &apos;Boston&apos;), ${/state})&quot;,
      &quot;inputFieldGroup&quot; : {
        &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
        &quot;actions&quot; : [ ],
        &quot;field&quot; : [ {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;docId&quot; : &quot;JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d&quot;,
          &quot;path&quot; : &quot;/addressList&lt;&gt;&quot;,
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
            &quot;actions&quot; : [ ],
            &quot;docId&quot; : &quot;JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d&quot;,
            &quot;path&quot; : &quot;/addressList&lt;0&gt;&quot;,
            &quot;fieldType&quot; : &quot;COMPLEX&quot;,
            &quot;field&quot; : [ {
              &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
              &quot;value&quot; : &quot;Bosto&quot;,
              &quot;docId&quot; : &quot;JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d&quot;,
              &quot;path&quot; : &quot;/addressList&lt;0&gt;/city&quot;,
              &quot;fieldType&quot; : &quot;STRING&quot;,
              &quot;name&quot; : &quot;city&quot;
            }, {
              &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
              &quot;value&quot; : &quot;MA&quot;,
              &quot;docId&quot; : &quot;JSONSchemaSource-8abe4de2-6bbb-4e8b-ba7a-c9c94b66001d&quot;,
              &quot;path&quot; : &quot;/addressList&lt;0&gt;/state&quot;,
              &quot;fieldType&quot; : &quot;STRING&quot;,
              &quot;name&quot; : &quot;state&quot;
            } ]
          } ]
        } ]
      },
      &quot;inputField&quot; : [ ],
      &quot;outputField&quot; : [ {
        &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
        &quot;value&quot; : &quot;MA&quot;,
        &quot;docId&quot; : &quot;JSONSchemaSource-ae6eae36-18ca-42e2-a2be-be5518c663b6&quot;,
        &quot;path&quot; : &quot;/addressList&lt;&gt;/city&quot;,
        &quot;fieldType&quot; : &quot;STRING&quot;,
        &quot;name&quot; : &quot;city&quot;
      } ],
      &quot;id&quot; : &quot;preview&quot;
    },
    &quot;audits&quot; : {
      &quot;audit&quot; : [ ]
    }
  }
</pre>

![fix1](https://user-images.githubusercontent.com/2981421/113038256-51cbcd00-9164-11eb-9c2d-fa6a5cb44f73.png)

**Closed** 2021-03-30 21:27 UTC
Labels: cat/enhancement, group/runtime, prio/p1
