### ISSUE TITLE
No field actions for Boolean, Short, Date 

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#225] opened 2018-01-08 13:12 UTC
Currently there is not possible to add transformation to Boolean, Short, Date fields. I'm not sure if it's intentional but I believe (at least) short should have similar transformation possibilities as integer.

**Comment by igarashitm** [comment] 2018-01-08 14:10
Hi @mmelko , are you seeing #107 ? This is a UI bug for sure, as we already have some transformations (aka field actions) which should show up for the `NUMBER` field types. And those `NUMBER` field actions should show up for the `Short` field as well.

@jpav do we have Boolean field actions?

**Comment by mmelko** [comment] 2018-01-08 14:20
yeah looks same, however in #107 it's about Number>Number transformations in general isn't ? I can see transformations for all number types except short.  Is it possible that Short isn't a NUMBER type for atlasmap ?

**Comment by igarashitm** [comment] 2018-01-08 14:27
It sounds like a variation of #107 bug. Short should be treated as a `NUMBER` for sure.

@rohanmars , can you take a look at this to see if it's easier for you to address this as a part of #107 ?

**Comment by pleacu** [comment] 2018-01-18 20:39
Hey - since this is my first crack at AtlasMap the more eyes on this the better!

The inital issue was that the 'Add Transformation' button wasn't showing up for some field types.
The MappingFieldActionComponent class has a method to return an array of applicable field actions
for the selected field pair types.  It walks all of the field actions as defined in the TransitionModel
and allows it to determine if we should add the field action to the array.  A non-zero array triggers
the 'Add Transformation' button.

The issue is with the FieldActionConfig class/ appliesToField method in the transition model.
It's basically only set up to work with 'STRING' and 'NUMBER' field actions.  It does go through
some effort to relate generic field action method 'STRING' and 'NUMBER' types to their
sources/targets field types but no other types.

What I did:

* Removed the "field" argument to the appliesToField() method - the field mapping pair was already
  being supplied.

* Made sure the field pair was already fully mapped.

* Checked for string and number types.

* Allowed non-primitive types if the selected field pair types matched the field action types.

Please see the test PR for details.

thkx!

**Comment by mmelko** [comment] 2018-01-22 15:01
Reopening because there are still no transformations when Boolean is involved (Boolean to String) into mapping. 
Also no transformation is possible when conversion (String<--> numbers) is necessary. I believe this is regression, it was possible to add transformation before.

**Comment by pleacu** [comment] 2018-01-22 20:20
Hey @mmelko , I relaxed the code to check target types when considering field actions.  There are no actions for target boolean but your  (Boolean to String)  should work now (and others).  Please reopen if it fails.

**Comment by igarashitm** [comment] 2018-01-22 20:40
merged (hmm, auto-close might not work 2nd time after reopen)

**Closed by igarashitm** 2018-01-22 20:40 UTC
Labels: cat/bug, module/ui

**Comment by mmelko** [comment] 2018-01-23 13:25
Looks good now, thanks !
